#The first line is used for comment
!counter 0x79 邪心教义指示物
!setname 0x2ea 塞尼特
!setname 0x2ec 异解△
!setname 0x2ed 盈彩月夜
!setname 0x2ee 龙札
!setname 0x2ef 太阳神
!setname 0x2f0 拉之翼神龙
!setname 0x2f1 轮回虫龙
!setname 0x2f2 白鸦