name: Mirror upstream repository

on:
  schedule:
    - cron: '0 7 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Clean Clone
        run: |
          rm -rf repo
          git clone --depth=1 --single-branch --branch master https://github.com/${{ github.repository }} repo
          cd repo
          git config user.name "Evolution Bot"
          git config user.email "bot@evolutionygo.com"
          git remote add upstream https://code.moenext.com/mycard/pre-release-database-cdb.git
          git fetch upstream master --depth=50
          FETCH_HEAD_SHA=$(git rev-parse FETCH_HEAD)
          git reset --hard ${FETCH_HEAD_SHA}
          echo "SYNC_OK=true" >> $GITHUB_ENV

      - name: Verify local repository integrity
        working-directory: repo
        run: git fsck --full

      - name: Push to origin
        if: env.SYNC_OK == 'true'
        working-directory: repo
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git remote remove origin
          git remote add origin https://x-access-token:${TOKEN}@github.com/${{ github.repository }}.git
          git push origin +HEAD:master --force --verbose