name: Mirror upstream repository

on:
  schedule:
    - cron: '0 7 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Clone master branch
        run: |
          git clone --depth=1 --single-branch --branch master https://github.com/${{ github.repository }} repo
          cd repo
          git config user.name "Evolution Bot"
          git config user.email "bot@evolutionygo.com"
          git remote add upstream https://code.moenext.com/mycard/pre-release-database-cdb.git
          git fetch upstream master --depth=1
          git reset --hard upstream/master
          echo "SYNC_OK=true" >> $GITHUB_ENV

      - name: Cleanup repository
        working-directory: repo
        run: git gc --prune=now

      - name: Push to origin
        if: env.SYNC_OK == 'true'
        working-directory: repo
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git remote remove origin
          git remote add origin https://x-access-token:${TOKEN}@github.com/${{ github.repository }}.git
          for i in {1..3}; do
            git push origin +HEAD:master --force && break || sleep 10;
          done